config/routes.rb
Krum::Application.routes.draw do
  root :to => 'groups#index'
  match '/admin' => 'application#admin_sign_in'

  resources :groups do
    collection do
      post :submit
    end
  end
  resources :events, :only => :index
end

app/models/group.rb
class Group
  include Mongoid::Document
  include Mongoid::Document::Taggable
  include Mongoid::Search
  include Mongoid::Timestamps

  field :name,        type: String
  field :url_1,       type: String
  field :url_2,       type: String
  field :email,       type: String
  field :description, type: String

  search_in :name, :description, :tags

  mount_uploader :avatar, AvatarUploader

  validates_presence_of :name, :url_1

  before_validation :clean_empty_tags

  default_scope order_by(:updated_at => :desc)

  def self.search_for(keyword)
    return self.scoped if keyword.blank?

    search(keyword)
  end

  private

  def clean_empty_tags
    tags.reject!{|t| t.strip.blank? } # jquery-chosen plugin sends an addtional blank
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :admin_signed_in?
  def admin_signed_in?
    !!session[:admin]
  end

  def admin_required
    redirect_to admin_path unless admin_signed_in?
  end

  def admin_sign_in
    if authenticate_or_request_with_http_basic do |user_name, password|
        admin_name = Krum.config.username
        admin_password = Krum.config.password
        if user_name == admin_name && password == admin_password
          session[:admin] = true
          redirect_to root_path and return true
        end
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :admin_required, :only => [:new, :create, :destroy]
  before_filter :load_group, :only => [:edit, :update, :destroy]

  def index
    @groups = Group.search_for(params[:q])
    @groups = @groups.page(params[:page]).per(10)

    respond_to do |format|
      format.html { @groups = GroupDecorator.decorate(@groups) }
      format.json { render :json => @groups.to_json(:except => :_keywords) }
    end
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      redirect_to groups_path, notice: "Group has been added successfully."
    else
      render :new
    end
  end

  def update
    if @group.update_attributes(params[:group])
      redirect_to groups_path, notice: "Group has been updated successfully."
    else
      render :edit
    end
  end

  def destroy
    @group.destroy

    redirect_to groups_path, notice: "Group has been deleted successfully."
  end

  def submit
    new_group = Group.new(params[:new_group])
    if new_group.valid?
      NotifierMailer.new_group(new_group).deliver
      flash[:notice] = "The group will be moderated, and hopefully it will be added to site soon."
    else
      flash[:error] = "You didn't complete all required information on form."
    end

    redirect_to :back
  end

  private

  def load_group
    @group = Group.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.haml
.page-header
  %h1 Events

#calendar
  =raw Krum.config.calendar

app/views/groups/_form.html.haml
= simple_form_for @group, :defaults => {:input_html => {:class => 'span5'}} do |f|
  = f.error_notification if f.error_notification

  = f.input :name
  = f.input :url_1, :as => :url
  = f.input :url_2, :as => :url
  = f.input :email, :as => :email
  = f.input :description, :as => :text, :hint => "Keep it concise in 1 or 2 sentences only.", :input_html => {:rows => 5}
  = f.input :tags, :collection => Group.tags, 
      :input_html => {"data-placeholder" => "Select tags", 'data-allows-new-values' => true, :class => 'chosen', :multiple => 'multiple' }
  = f.input :avatar

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to "Cancel", root_path, :class => "btn btn-danger" 

app/views/groups/_group_card.html.haml
%li.span4
  %div.group-card.thumbnail[group.model]
    - if admin_signed_in?
      .action
        = group.edit_link
        = group.delete_link

    .header
      %p= group.logo_link
      %p.group-name= group.name_link
    .caption
      %p= group.url_2_link
      %p= group.email_link
      %p.description= group.description
      = render 'tags', tags: group.tags

app/views/groups/_tags.html.haml
%ul.tags
  - tags.each do |tag|
    %li
      %span.label.label-info= tag

app/views/groups/edit.html.haml
.page-header
  %h1 Edit Group

= render 'form'

app/views/groups/index.html.haml
.page-header
  %h1 Find your interest groups
  .span3.offset9.new-group= link_to "Add New Group", new_group_path, :class => "btn btn-primary" if admin_signed_in?

%ul#groups.thumbnails
  = render partial: 'group_card', collection: @groups, as: :group

= paginate @groups

app/views/groups/index.js.erb
<%= j render(partial: 'group_card', collection: @groups, as: :group) %>

app/views/groups/new.html.haml
= simple_form_for @group, :defaults => {:input_html => {:class => 'span5'}} do |f|
  = f.error_notification if f.error_notification

  %legend New Group

  = f.input :name
  = f.input :url_1, :as => :url
  = f.input :url_2, :as => :url
  = f.input :email, :as => :email
  = f.input :description, :as => :text, :hint => "Keep it concise in 1 or 2 sentences only.", :input_html => {:rows => 5}
  = f.input :tags, :collection => Group.tags, 
      :input_html => {"data-placeholder" => "Select tags", 'data-allows-new-values' => true, :class => 'chosen', :multiple => 'multiple' }
  = f.input :avatar

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = submit_tag 'Cancel', :type => :reset, :title => "Reset form", :class => "btn btn-danger"

app/views/layouts/_flash.html.haml
- flash().each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = msg

app/views/layouts/_footer.html.haml
%footer.page-footer.navbar-inner
  .container
    .description
      %p Designed and built by #{ link_to "Samnang Chhun", "http://wowkhmer.com", target: "_blank" }
      %p Source code is available on #{ link_to "GitHub", "https://github.com/samnang/krum", target: "_blank" }
    .logo
      = link_to image_tag("sharevision_logo.png", alt: "ShareVision Team"), 
                "http://www.sharevisionteam.org/", 
                target: "blank",
                title: "ShareVision Team"

app/views/layouts/_ga.html.haml
:javascript

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-10806853-4']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_navigation.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.brand{href: root_path}
        Krum
      %ul.nav
        %li{class: ("active" if controller_name == "groups")}
          = link_to "Groups", groups_path
        %li{class: ("active" if controller_name == "events")}
          = link_to "Events", events_path
      %form.navbar-search.pull-right{action: groups_path}
        %input.search-query.span3{name: "q", value: params[:q], placeholder: "Search", type: "text"}
        %input.submit-button{value: "Search", type: "submit"}

app/views/layouts/_submit_new_group.html.haml
#new-group-modal.modal.hide.fade
  = simple_form_for :new_group, url: submit_groups_path do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Submit New Group
    .modal-body
      %span.label.label-info Note
      New group will not show immediately, it will send to administrator to be moderated.
      %legend New Group
      = f.input :name
      = f.input :url_1, :as => :url, :label => "Url"
      = f.input :email, :as => :email, :required => false
      = f.input :tags, :collection => Group.tags, :required => false,
          :input_html => {"data-placeholder" => "Choose tags", :class => 'chosen', :multiple => 'multiple' }
    .modal-footer
      = f.submit 'Submit', :class => 'btn btn-primary'
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

%a.btn.btn-primary.submit-new-group Submit New Group

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %meta{charset: "utf-8"}
    %meta{content: "Krum - ShareVision Team, a directory to list groups in Cambodia local communities, so it could helps people that have the same interests found each other.", name: "description"}
    %title Krum - ShareVision Team
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = favicon_link_tag
    = render 'layouts/ga' if Rails.env.production?

  %body
    %header
      = render 'layouts/navigation'
    #main.container
      = render 'layouts/flash'
      = yield
    = render 'layouts/footer'

    = render 'layouts/submit_new_group'